FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY ./frontend /app/frontend
RUN npm run build

FROM nginx:stable-alpine AS runner

COPY --from=builder /app/frontend /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
